version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: laughingpotato
      POSTGRES_PASSWORD: laughingpotato
      POSTGRES_DB: laughingpotato
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "laughingpotato"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: ""
    environment:
      LAUGHINGPOTATO_DJANGO_SECRET: "mysupersecretsecret"
      LAUGHINGPOTATO_DJANGO_DEBUG: "True"
      LAUGHINGPOTATO_DJANGO_ALLOWED_HOSTS: "*"
      LAUGHINGPOTATO_BASE_URL: "/"
      LAUGHINGPOTATO_DB_DEFAULT: "postgres://laughingpotato:laughingpotato@db/laughingpotato"
      LAUGHINGPOTATO_LOG_LEVEL: "INFO"
    ports:
      - "8003:8000"
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
