# Generated by Django 4.2.1 on 2023-05-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_report_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportlinelabel",
            name="client",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="api.client"
            ),
            preserve_default=False,
        ),
    ]
